import type { GlobalConfig } from 'payload'

export const DefaultPlans: GlobalConfig = {
  slug: 'default-plans',
  label: 'Default Plans',
  access: {
    read: () => true,
    update: ({ req: { user } }) => user?.role === 'admin',
  },
  fields: [
    {
      name: 'defaultWorkoutPlan',
      label: 'Default Workout Plan',
      type: 'json',
      required: true,
      defaultValue: {
        sunday: {
          title: 'Upper Body Strength',
          duration: 60,
          entries: [
            { name: 'Warmup', reps: '10 min', sets: 1, weight: '-' },
            { name: 'Bench Press', reps: '8 rep', sets: 4, weight: '40 kg' },
            { name: 'Shoulder Press', reps: '10 rep', sets: 3, weight: '25 kg' },
            { name: 'Push Up', reps: '12 rep', sets: 3, weight: 'Body Weight' },
            { name: 'Pull Ups', reps: '12 rep', sets: 3, weight: 'Body Weight' },
            { name: 'Bicep Curls', reps: '15 rep', sets: 3, weight: '25 kg' },
          ],
        },
        monday: {
          title: 'Lower Body Strength',
          duration: 60,
          entries: [
            { name: 'Warmup', reps: '10 min', sets: 1, weight: '-' },
            { name: 'Squats', reps: '10 rep', sets: 4, weight: '60 kg' },
            { name: 'Deadlifts', reps: '8 rep', sets: 3, weight: '80 kg' },
            { name: 'Leg Press', reps: '12 rep', sets: 3, weight: '100 kg' },
            { name: 'Lunges', reps: '12 rep', sets: 3, weight: 'Body Weight' },
            { name: 'Calf Raises', reps: '15 rep', sets: 3, weight: '30 kg' },
          ],
        },
        tuesday: {
          title: 'Cardio & Core',
          duration: 45,
          entries: [
            { name: 'Warmup', reps: '5 min', sets: 1, weight: '-' },
            { name: 'Treadmill Run', reps: '20 min', sets: 1, weight: '-' },
            { name: 'Planks', reps: '60 sec', sets: 3, weight: 'Body Weight' },
            { name: 'Mountain Climbers', reps: '30 rep', sets: 3, weight: 'Body Weight' },
            { name: 'Russian Twists', reps: '20 rep', sets: 3, weight: '10 kg' },
            { name: 'Leg Raises', reps: '15 rep', sets: 3, weight: 'Body Weight' },
          ],
        },
        wednesday: {
          title: 'Chest & Triceps',
          duration: 60,
          entries: [
            { name: 'Warmup', reps: '10 min', sets: 1, weight: '-' },
            { name: 'Incline Bench Press', reps: '8 rep', sets: 4, weight: '35 kg' },
            { name: 'Cable Flyes', reps: '12 rep', sets: 3, weight: '20 kg' },
            { name: 'Dips', reps: '12 rep', sets: 3, weight: 'Body Weight' },
            { name: 'Tricep Pushdowns', reps: '15 rep', sets: 3, weight: '25 kg' },
            { name: 'Overhead Tricep Extension', reps: '12 rep', sets: 3, weight: '15 kg' },
          ],
        },
        thursday: {
          title: 'Back & Biceps',
          duration: 60,
          entries: [
            { name: 'Warmup', reps: '10 min', sets: 1, weight: '-' },
            { name: 'Barbell Rows', reps: '8 rep', sets: 4, weight: '50 kg' },
            { name: 'Lat Pulldowns', reps: '10 rep', sets: 3, weight: '40 kg' },
            { name: 'Seated Cable Rows', reps: '12 rep', sets: 3, weight: '35 kg' },
            { name: 'Hammer Curls', reps: '12 rep', sets: 3, weight: '20 kg' },
            { name: 'Barbell Curls', reps: '10 rep', sets: 3, weight: '25 kg' },
          ],
        },
        friday: {
          title: 'Shoulders & Arms',
          duration: 55,
          entries: [
            { name: 'Warmup', reps: '10 min', sets: 1, weight: '-' },
            { name: 'Military Press', reps: '8 rep', sets: 4, weight: '30 kg' },
            { name: 'Lateral Raises', reps: '12 rep', sets: 3, weight: '12 kg' },
            { name: 'Front Raises', reps: '12 rep', sets: 3, weight: '10 kg' },
            { name: 'Rear Delt Flyes', reps: '15 rep', sets: 3, weight: '8 kg' },
            { name: 'Preacher Curls', reps: '10 rep', sets: 3, weight: '20 kg' },
          ],
        },
        saturday: {
          title: 'Rest',
          duration: 0,
          entries: [],
        },
      },
    },
    {
      name: 'defaultMealPlan',
      label: 'Default Meal Plan',
      type: 'json',
      required: true,
      defaultValue: {
        sunday: [
          {
            name: 'Greek Yogurt Bowl',
            slot: 'Breakfast',
            calories: 500,
            protein: 28,
            carbs: 55,
            fats: 12,
            description: 'Greek yogurt with granola and fresh berries',
          },
          {
            name: 'Grilled Chicken Rice Bowl',
            slot: 'Lunch',
            calories: 700,
            protein: 40,
            carbs: 70,
            fats: 20,
            description: 'Grilled chicken breast with brown rice and mixed vegetables',
          },
          {
            name: 'Mixed Nuts + Banana',
            slot: 'Snacks',
            calories: 350,
            protein: 6,
            carbs: 28,
            fats: 22,
            description: 'Handful of mixed nuts with a medium banana',
          },
          {
            name: 'Salmon + Veggies',
            slot: 'Dinner',
            calories: 600,
            protein: 33,
            carbs: 25,
            fats: 32,
            description: 'Baked salmon with roasted seasonal vegetables',
          },
        ],
        monday: [
          {
            name: 'Oats with Peanut Butter',
            slot: 'Breakfast',
            calories: 520,
            protein: 22,
            carbs: 60,
            fats: 18,
            description: 'Steel-cut oats with peanut butter and banana',
          },
          {
            name: 'Turkey Wrap + Salad',
            slot: 'Lunch',
            calories: 680,
            protein: 35,
            carbs: 58,
            fats: 22,
            description: 'Whole wheat wrap with turkey and garden salad',
          },
          {
            name: 'Protein Bar',
            slot: 'Snacks',
            calories: 300,
            protein: 20,
            carbs: 25,
            fats: 9,
            description: 'High-protein energy bar',
          },
          {
            name: 'Stir-Fried Tofu + Rice',
            slot: 'Dinner',
            calories: 580,
            protein: 28,
            carbs: 65,
            fats: 14,
            description: 'Tofu stir-fry with jasmine rice',
          },
        ],
        tuesday: [
          {
            name: 'Smoothie Bowl',
            slot: 'Breakfast',
            calories: 450,
            protein: 20,
            carbs: 65,
            fats: 10,
            description: 'Acai smoothie bowl with granola and fruits',
          },
          {
            name: 'Beef Stir Fry',
            slot: 'Lunch',
            calories: 720,
            protein: 40,
            carbs: 55,
            fats: 32,
            description: 'Lean beef with mixed vegetables and noodles',
          },
          {
            name: 'Apple + Peanut Butter',
            slot: 'Snacks',
            calories: 310,
            protein: 7,
            carbs: 30,
            fats: 18,
            description: 'Fresh apple slices with natural peanut butter',
          },
          {
            name: 'Chicken Pasta',
            slot: 'Dinner',
            calories: 650,
            protein: 35,
            carbs: 70,
            fats: 15,
            description: 'Whole grain pasta with grilled chicken',
          },
        ],
        wednesday: [
          {
            name: 'Scrambled Eggs + Toast',
            slot: 'Breakfast',
            calories: 480,
            protein: 25,
            carbs: 40,
            fats: 20,
            description: 'Scrambled eggs with whole grain toast',
          },
          {
            name: 'Chicken Buddha Bowl',
            slot: 'Lunch',
            calories: 690,
            protein: 38,
            carbs: 65,
            fats: 24,
            description: 'Chicken with quinoa, avocado, and veggies',
          },
          {
            name: 'Yogurt Cup',
            slot: 'Snacks',
            calories: 200,
            protein: 12,
            carbs: 22,
            fats: 6,
            description: 'Greek yogurt with honey',
          },
          {
            name: 'Tuna Rice Bowl',
            slot: 'Dinner',
            calories: 600,
            protein: 32,
            carbs: 50,
            fats: 18,
            description: 'Tuna with brown rice and edamame',
          },
        ],
        thursday: [
          {
            name: 'Chia Pudding + Fruits',
            slot: 'Breakfast',
            calories: 430,
            protein: 18,
            carbs: 45,
            fats: 14,
            description: 'Chia seed pudding with mixed berries',
          },
          {
            name: 'Paneer Rice Bowl',
            slot: 'Lunch',
            calories: 700,
            protein: 32,
            carbs: 65,
            fats: 26,
            description: 'Paneer tikka with basmati rice',
          },
          {
            name: 'Mixed Nuts',
            slot: 'Snacks',
            calories: 280,
            protein: 5,
            carbs: 10,
            fats: 23,
            description: 'Assorted roasted nuts',
          },
          {
            name: 'Chicken Soup + Toast',
            slot: 'Dinner',
            calories: 540,
            protein: 28,
            carbs: 45,
            fats: 12,
            description: 'Hearty chicken soup with whole grain toast',
          },
        ],
        friday: [
          {
            name: 'Avocado Toast + Egg',
            slot: 'Breakfast',
            calories: 520,
            protein: 22,
            carbs: 42,
            fats: 26,
            description: 'Mashed avocado on toast with poached egg',
          },
          {
            name: 'Beef Burrito Bowl',
            slot: 'Lunch',
            calories: 730,
            protein: 42,
            carbs: 70,
            fats: 25,
            description: 'Beef with rice, beans, and fresh toppings',
          },
          {
            name: 'Granola Bar',
            slot: 'Snacks',
            calories: 250,
            protein: 8,
            carbs: 35,
            fats: 8,
            description: 'Homemade granola energy bar',
          },
          {
            name: 'Veg Pasta + Tofu',
            slot: 'Dinner',
            calories: 620,
            protein: 30,
            carbs: 75,
            fats: 14,
            description: 'Vegetable pasta with crispy tofu',
          },
        ],
        saturday: [
          {
            name: 'Pancakes + Berries',
            slot: 'Breakfast',
            calories: 550,
            protein: 20,
            carbs: 70,
            fats: 18,
            description: 'Whole wheat pancakes with fresh berries and honey',
          },
          {
            name: 'Grilled Fish + Salad',
            slot: 'Lunch',
            calories: 650,
            protein: 38,
            carbs: 45,
            fats: 28,
            description: 'Grilled fish fillet with mixed green salad',
          },
          {
            name: 'Trail Mix',
            slot: 'Snacks',
            calories: 320,
            protein: 8,
            carbs: 30,
            fats: 20,
            description: 'Dried fruits, nuts, and seeds mix',
          },
          {
            name: 'Quinoa Stuffed Bell Peppers',
            slot: 'Dinner',
            calories: 580,
            protein: 25,
            carbs: 68,
            fats: 16,
            description: 'Bell peppers stuffed with quinoa and vegetables',
          },
        ],
      },
    },
  ],
}
