/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'user-fitness': UserFitness;
    attendance: Attendance;
    'gym-counts': GymCount;
    notices: Notice;
    subscription: Subscription;
    transaction: Transaction;
    payments: Payment;
    'trainer-profiles': TrainerProfile;
    'plan-requests': PlanRequest;
    'trainee-assignments': TraineeAssignment;
    'plan-versions': PlanVersion;
    'workout-plans': WorkoutPlan;
    'meal-plans': MealPlan;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'user-fitness': UserFitnessSelect<false> | UserFitnessSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    'gym-counts': GymCountsSelect<false> | GymCountsSelect<true>;
    notices: NoticesSelect<false> | NoticesSelect<true>;
    subscription: SubscriptionSelect<false> | SubscriptionSelect<true>;
    transaction: TransactionSelect<false> | TransactionSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'trainer-profiles': TrainerProfilesSelect<false> | TrainerProfilesSelect<true>;
    'plan-requests': PlanRequestsSelect<false> | PlanRequestsSelect<true>;
    'trainee-assignments': TraineeAssignmentsSelect<false> | TraineeAssignmentsSelect<true>;
    'plan-versions': PlanVersionsSelect<false> | PlanVersionsSelect<true>;
    'workout-plans': WorkoutPlansSelect<false> | WorkoutPlansSelect<true>;
    'meal-plans': MealPlansSelect<false> | MealPlansSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    home: Home;
    navbar: Navbar;
    reviews: Review;
    'default-plans': DefaultPlan;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'default-plans': DefaultPlansSelect<false> | DefaultPlansSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  profilePicture?: (string | null) | Media;
  dob?: string | null;
  phoneNumber?: string | null;
  gender?: ('male' | 'female' | 'other') | null;
  role: 'admin' | 'trainer' | 'user';
  plan?: ('essential' | 'premium' | 'elite') | null;
  currentTrainer?: (string | null) | User;
  nextPaymentDate?: string | null;
  OTP?: string | null;
  email_verified?: boolean | null;
  password_set?: boolean | null;
  otpflag?: boolean | null;
  payment?: boolean | null;
  khaltiPidx?: string | null;
  paymentOrderId?: string | null;
  passwordResetToken?: string | null;
  passwordResetExpiry?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-fitness".
 */
export interface UserFitness {
  id: string;
  user: string | User;
  goals?: ('weight_loss' | 'muscle_building' | 'toning' | 'conditioning' | 'mobility' | 'maintenance')[] | null;
  bodyMetrics?: {
    height?: number | null;
    currentWeight?: number | null;
    targetWeight?: number | null;
  };
  dailyCalories?: {
    target?: number | null;
    consumed?: number | null;
    burned?: number | null;
  };
  mealPlan?: {
    dietType?: ('vegetarian' | 'non_vegetarian' | 'vegan' | 'pescatarian') | null;
    allergies?:
      | {
          allergen?: string | null;
          id?: string | null;
        }[]
      | null;
    preferences?: string | null;
  };
  workoutPlan?: {
    frequency?: number | null;
    preferredDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[] | null;
    duration?: number | null;
    preferredTypes?: ('cardio' | 'strength' | 'yoga' | 'hiit' | 'sports')[] | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: string;
  user: string | User;
  role: 'member' | 'trainer';
  date: string;
  /**
   * Format: HH:MM (24-hour format, e.g., 09:30)
   */
  checkInTime?: string | null;
  /**
   * Format: HH:MM (24-hour format, e.g., 18:45)
   */
  checkOutTime?: string | null;
  /**
   * Automatically calculated from check-in and check-out times
   */
  durationMinutes?: number | null;
  /**
   * Status is "absent" if no check-in/check-out time is provided
   */
  status: 'checked-in' | 'checked-out' | 'auto-closed' | 'absent' | 'present';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gym-counts".
 */
export interface GymCount {
  id: string;
  date: string;
  currentMembers?: number | null;
  currentTrainers?:
    | {
        trainer?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices".
 */
export interface Notice {
  id: string;
  /**
   * Notice title or headline
   */
  title: string;
  /**
   * Date of the notice or event
   */
  date: string;
  /**
   * Notice priority level
   */
  type: 'important' | 'warning' | 'reminder';
  /**
   * Optional detailed description of the notice
   */
  description?: string | null;
  /**
   * Toggle to show/hide this notice
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription".
 */
export interface Subscription {
  id: string;
  name: string;
  price: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transaction".
 */
export interface Transaction {
  id: string;
  user: string | User;
  amount: number;
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  stripeTransactionId?: string | null;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: string;
  user: string | User;
  orderId: string;
  khaltiPidx?: string | null;
  plan: 'essential' | 'premium' | 'elite';
  amount: number;
  status: 'pending' | 'initiated' | 'completed' | 'failed' | 'refunded';
  paymentMethod?: ('khalti' | 'cash' | 'bank_transfer') | null;
  paymentType: 'signup' | 'renewal';
  paidAt?: string | null;
  validUntil?: string | null;
  khaltiTransactionId?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainer-profiles".
 */
export interface TrainerProfile {
  id: string;
  user: string | User;
  status?: ('active' | 'pending' | 'paused') | null;
  specializations?:
    | ('weight_loss' | 'muscle_building' | 'toning' | 'conditioning' | 'mobility' | 'maintenance')[]
    | null;
  workingDays: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[];
  workingHours: {
    start: string;
    end: string;
    timezone?: string | null;
  };
  notes?: string | null;
  avgResponseMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-requests".
 */
export interface PlanRequest {
  id: string;
  user: string | User;
  /**
   * Reference to user fitness profile for trainer context
   */
  userFitnessData?: (string | null) | UserFitness;
  goals?: ('weight_loss' | 'muscle_building' | 'toning' | 'conditioning' | 'mobility' | 'maintenance')[] | null;
  tier: 'premium' | 'elite';
  /**
   * Trainer specializations that matched user goals
   */
  matchedSpecializations?:
    | {
        specialization?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Number of goals that matched trainer specializations
   */
  matchScore?: number | null;
  assignedTrainer?: (string | null) | User;
  status?: ('pending' | 'accepted' | 'rejected') | null;
  respondedAt?: string | null;
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainee-assignments".
 */
export interface TraineeAssignment {
  id: string;
  user: string | User;
  trainer: string | User;
  status?: ('active' | 'paused' | 'ended') | null;
  planStatus?: ('pending' | 'active' | 'revision') | null;
  startedAt?: string | null;
  planSentAt?: string | null;
  endedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-versions".
 */
export interface PlanVersion {
  id: string;
  user: string | User;
  trainer?: (string | null) | User;
  type: 'workout' | 'meal';
  source?: ('generic' | 'trainer' | 'ai') | null;
  status?: ('draft' | 'submitted' | 'active' | 'inactive') | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  activatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-plans".
 */
export interface WorkoutPlan {
  id: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meal-plans".
 */
export interface MealPlan {
  id: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'user-fitness';
        value: string | UserFitness;
      } | null)
    | ({
        relationTo: 'attendance';
        value: string | Attendance;
      } | null)
    | ({
        relationTo: 'gym-counts';
        value: string | GymCount;
      } | null)
    | ({
        relationTo: 'notices';
        value: string | Notice;
      } | null)
    | ({
        relationTo: 'subscription';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'transaction';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'payments';
        value: string | Payment;
      } | null)
    | ({
        relationTo: 'trainer-profiles';
        value: string | TrainerProfile;
      } | null)
    | ({
        relationTo: 'plan-requests';
        value: string | PlanRequest;
      } | null)
    | ({
        relationTo: 'trainee-assignments';
        value: string | TraineeAssignment;
      } | null)
    | ({
        relationTo: 'plan-versions';
        value: string | PlanVersion;
      } | null)
    | ({
        relationTo: 'workout-plans';
        value: string | WorkoutPlan;
      } | null)
    | ({
        relationTo: 'meal-plans';
        value: string | MealPlan;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  profilePicture?: T;
  dob?: T;
  phoneNumber?: T;
  gender?: T;
  role?: T;
  plan?: T;
  currentTrainer?: T;
  nextPaymentDate?: T;
  OTP?: T;
  email_verified?: T;
  password_set?: T;
  otpflag?: T;
  payment?: T;
  khaltiPidx?: T;
  paymentOrderId?: T;
  passwordResetToken?: T;
  passwordResetExpiry?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-fitness_select".
 */
export interface UserFitnessSelect<T extends boolean = true> {
  user?: T;
  goals?: T;
  bodyMetrics?:
    | T
    | {
        height?: T;
        currentWeight?: T;
        targetWeight?: T;
      };
  dailyCalories?:
    | T
    | {
        target?: T;
        consumed?: T;
        burned?: T;
      };
  mealPlan?:
    | T
    | {
        dietType?: T;
        allergies?:
          | T
          | {
              allergen?: T;
              id?: T;
            };
        preferences?: T;
      };
  workoutPlan?:
    | T
    | {
        frequency?: T;
        preferredDays?: T;
        duration?: T;
        preferredTypes?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  user?: T;
  role?: T;
  date?: T;
  checkInTime?: T;
  checkOutTime?: T;
  durationMinutes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gym-counts_select".
 */
export interface GymCountsSelect<T extends boolean = true> {
  date?: T;
  currentMembers?: T;
  currentTrainers?:
    | T
    | {
        trainer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices_select".
 */
export interface NoticesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  type?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription_select".
 */
export interface SubscriptionSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transaction_select".
 */
export interface TransactionSelect<T extends boolean = true> {
  user?: T;
  amount?: T;
  status?: T;
  stripeTransactionId?: T;
  notes?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  user?: T;
  orderId?: T;
  khaltiPidx?: T;
  plan?: T;
  amount?: T;
  status?: T;
  paymentMethod?: T;
  paymentType?: T;
  paidAt?: T;
  validUntil?: T;
  khaltiTransactionId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainer-profiles_select".
 */
export interface TrainerProfilesSelect<T extends boolean = true> {
  user?: T;
  status?: T;
  specializations?: T;
  workingDays?: T;
  workingHours?:
    | T
    | {
        start?: T;
        end?: T;
        timezone?: T;
      };
  notes?: T;
  avgResponseMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-requests_select".
 */
export interface PlanRequestsSelect<T extends boolean = true> {
  user?: T;
  userFitnessData?: T;
  goals?: T;
  tier?: T;
  matchedSpecializations?:
    | T
    | {
        specialization?: T;
        id?: T;
      };
  matchScore?: T;
  assignedTrainer?: T;
  status?: T;
  respondedAt?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainee-assignments_select".
 */
export interface TraineeAssignmentsSelect<T extends boolean = true> {
  user?: T;
  trainer?: T;
  status?: T;
  planStatus?: T;
  startedAt?: T;
  planSentAt?: T;
  endedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-versions_select".
 */
export interface PlanVersionsSelect<T extends boolean = true> {
  user?: T;
  trainer?: T;
  type?: T;
  source?: T;
  status?: T;
  payload?: T;
  activatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-plans_select".
 */
export interface WorkoutPlansSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meal-plans_select".
 */
export interface MealPlansSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  heroSection: {
    backgroundImage: string | Media;
    title: string;
    subtitle?: string | null;
  };
  ctaButton1: {
    text: string;
    href: string;
  };
  ctaButton2: {
    text: string;
    href: string;
  };
  galleryImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: string;
  logo: string | Media;
  navLinks?:
    | {
        title: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    text: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  reviews?:
    | {
        name: string;
        email: string;
        message: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-plans".
 */
export interface DefaultPlan {
  id: string;
  defaultWorkoutPlan:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  defaultMealPlan:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        backgroundImage?: T;
        title?: T;
        subtitle?: T;
      };
  ctaButton1?:
    | T
    | {
        text?: T;
        href?: T;
      };
  ctaButton2?:
    | T
    | {
        text?: T;
        href?: T;
      };
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        title?: T;
        href?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviews?:
    | T
    | {
        name?: T;
        email?: T;
        message?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-plans_select".
 */
export interface DefaultPlansSelect<T extends boolean = true> {
  defaultWorkoutPlan?: T;
  defaultMealPlan?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}